spring:
  datasource:
    url: jdbc:h2:~/security-test;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect